export const POPUP_TYPE = {
  CONFIRM: 'CONFIRM',
  INFO_TUTOR: 'INFO_TUTOR',
  CALL_VIDEO: 'CALL_VIDEO',
  SCHEDULE_REGISTER: 'SCHEDULE_REGISTER',
  SELECT_TIME_MODAL: 'SELECT_TIME_MODAL',
  RATING_MODAL: 'RATING_MODAL',
  PAYMENT_MODAL: 'PAYMENT_MODAL',
  TRANSACTION_MODAL: 'TRANSACTION_MODAL',
};
